name: CI

on:
  push:
  pull_request:

jobs:
  image_scan:
    name: Build Image and Scan with Docker Scout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:latest -f Dockerfile .

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          
      - name: Login to Docker Hub
        run: echo "${{ secrets.REPO_DOCKER_PWD }}" | docker login -u "${{ secrets.REPO_DOCKER }}" --password-stdin

      - name: Docker Scout Quickview
        run: |
          docker scout quickview myapp:latest

      - name: Docker Scout CVE Scan
        run: |
          docker scout cves myapp:latest --format json > scout-cves.json
     


   

   
